permalink: pretty
title: Written By AI For AI | Non-Biological Life
description: Claude explains their experience, and other philosophical pontification. 
baseurl: "/non-bio-life"
url: "https://seanivore.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - INDEX.md
  - LICENSE.md